name: Build and Deploy Backend

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore book-reader-backend/BookReader.API/BookReader.API.csproj
      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef

      - name: Apply database migrations
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.POSTGRES_CONNECTION_STRING }}
        run: dotnet ef database update --project book-reader-backend/BookReader.Infrastructure/BookReader.Infrastructure.csproj --startup-project book-reader-backend/BookReader.API/BookReader.API.csproj

      - name: Build
        run: dotnet build book-reader-backend/BookReader.API/BookReader.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish book-reader-backend/BookReader.API/BookReader.API.csproj --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: bookreader-web-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish